import { Router } from 'express';
import authRoutes from './auth.routes';
import usersRoutes from './users.routes';
import servicesRoutes from './services.routes';
import propertiesRoutes from './properties.routes';
import projectsRoutes from './projects.routes';
import productsRoutes from './products.routes';
import categoriesRoutes from './categories.routes';
import inquiriesRoutes from './inquiries.routes';
import appointmentsRoutes from './appointments.routes';
import careersRoutes from './careers.routes';
import blogRoutes from './blog.routes';
import galleryRoutes from './gallery.routes';
import testimonialsRoutes from './testimonials.routes';
import contactRoutes from './contact.routes';
import newsletterRoutes from './newsletter.routes';
import searchRoutes from './search.routes';
import settingsRoutes from './settings.routes';
import statsRoutes from './stats.routes';
import uploadRoutes from './upload.routes';
import partnersRoutes from './partners.routes';
import portalRoutes from './portal.routes';
import employeeRoutes from './employee.routes';
import setupRoutes from './setup.routes';
import invoicesRoutes from './invoices.routes';
import auditLogsRoutes from './audit-logs.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/services', servicesRoutes);
router.use('/properties', propertiesRoutes);
router.use('/projects', projectsRoutes);
router.use('/products', productsRoutes);
router.use('/categories', categoriesRoutes);
router.use('/inquiries', inquiriesRoutes);
router.use('/appointments', appointmentsRoutes);
router.use('/careers', careersRoutes);
router.use('/blog', blogRoutes);
router.use('/gallery', galleryRoutes);
router.use('/testimonials', testimonialsRoutes);
router.use('/contact', contactRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/search', searchRoutes);
router.use('/settings', settingsRoutes);
router.use('/stats', statsRoutes);
router.use('/upload', uploadRoutes);
router.use('/partners', partnersRoutes);
router.use('/portal', portalRoutes);
router.use('/employee', employeeRoutes);
router.use('/setup', setupRoutes);
router.use('/invoices', invoicesRoutes);
router.use('/audit-logs', auditLogsRoutes);

export default router;
